### ISSUE TITLE
Ошибка при установке сертификата. Неправильный пароль

### ISSUE THREAD

**Issue by KoNOnOFFRUS** [Host-to-Host-Instructions/alfalink-1c-directbank-via-1c#24]
при установке сертификата "directBank_cert_psw_123456.pfx" на ОС win 2016 x64 - ошибка "Неправильный Пароль "

![2024-08-28_11-38-23](https://github.com/user-attachments/assets/21a12d6f-5750-43bd-99f3-871daf75189f)

корневой сертификат- установлен.

**Comment by KateBold** [comment]
Добрый день.
Вопрос решен по почте.
