### ISSUE TITLE
некорректно указаны настройки ООО МАНИ

### ISSUE THREAD

**Issue by KoNOnOFFRUS** [Host-to-Host-Instructions/alfalink-1c-directbank-via-1c#25]
для <html>
<body>

Краткое наименование | ООО "МАНИ"
-- | --

</body>
</html>

некорректно указаны параметры организации.
не указан КПП . из-за этого ошибка при загрузке настроек подключения.
надо добавить КПП 047364514

**Comment by KateBold** [comment]
Добрый день.
КПП указан в файле настроек, который необходимо загрузить для корректной работы 
![Clipboard - 28 августа 2024 г , 14_48 (1)](https://github.com/user-attachments/assets/d3a52aeb-a264-4371-839f-562f43e51e6f)
